# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\TosoProgram\TosoFrame\TosoFrame\res_Stat\Stat_UnitCostEditor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Stat_UnitCostEditor(object):
    def setupUi(self, Stat_UnitCostEditor):
        Stat_UnitCostEditor.setObjectName(_fromUtf8("Stat_UnitCostEditor"))
        Stat_UnitCostEditor.resize(838, 799)
        Stat_UnitCostEditor.setMinimumSize(QtCore.QSize(700, 765))
        self.tableWidget = QtGui.QTableWidget(Stat_UnitCostEditor)
        self.tableWidget.setGeometry(QtCore.QRect(30, 240, 781, 491))
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btn_load = QtGui.QPushButton(Stat_UnitCostEditor)
        self.btn_load.setEnabled(True)
        self.btn_load.setGeometry(QtCore.QRect(760, 10, 61, 25))
        self.btn_load.setObjectName(_fromUtf8("btn_load"))
        self.btn_submit = QtGui.QPushButton(Stat_UnitCostEditor)
        self.btn_submit.setEnabled(True)
        self.btn_submit.setGeometry(QtCore.QRect(690, 740, 121, 41))
        self.btn_submit.setObjectName(_fromUtf8("btn_submit"))
        self.btn_addrow = QtGui.QPushButton(Stat_UnitCostEditor)
        self.btn_addrow.setEnabled(True)
        self.btn_addrow.setGeometry(QtCore.QRect(30, 210, 61, 25))
        self.btn_addrow.setObjectName(_fromUtf8("btn_addrow"))
        self.btn_delrow = QtGui.QPushButton(Stat_UnitCostEditor)
        self.btn_delrow.setEnabled(True)
        self.btn_delrow.setGeometry(QtCore.QRect(90, 210, 61, 25))
        self.btn_delrow.setObjectName(_fromUtf8("btn_delrow"))
        self.label_8 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_8.setGeometry(QtCore.QRect(384, 121, 70, 20))
        self.label_8.setMinimumSize(QtCore.QSize(70, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_avgW = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_avgW.setGeometry(QtCore.QRect(460, 121, 250, 20))
        self.lineEdit_avgW.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_avgW.setObjectName(_fromUtf8("lineEdit_avgW"))
        self.label_9 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_9.setGeometry(QtCore.QRect(384, 148, 70, 20))
        self.label_9.setMinimumSize(QtCore.QSize(70, 20))
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lineEdit_avgH = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_avgH.setGeometry(QtCore.QRect(460, 148, 250, 20))
        self.lineEdit_avgH.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_avgH.setObjectName(_fromUtf8("lineEdit_avgH"))
        self.lineEdit_cata = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_cata.setEnabled(False)
        self.lineEdit_cata.setGeometry(QtCore.QRect(108, 67, 250, 20))
        self.lineEdit_cata.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_cata.setObjectName(_fromUtf8("lineEdit_cata"))
        self.label = QtGui.QLabel(Stat_UnitCostEditor)
        self.label.setGeometry(QtCore.QRect(32, 13, 70, 20))
        self.label.setMinimumSize(QtCore.QSize(70, 20))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.lineEdit_code = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_code.setGeometry(QtCore.QRect(108, 13, 250, 20))
        self.lineEdit_code.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_code.setObjectName(_fromUtf8("lineEdit_code"))
        self.label_2 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_2.setGeometry(QtCore.QRect(32, 40, 70, 20))
        self.label_2.setMinimumSize(QtCore.QSize(70, 20))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lineEdit_name = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_name.setEnabled(False)
        self.lineEdit_name.setGeometry(QtCore.QRect(108, 40, 250, 20))
        self.lineEdit_name.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_name.setObjectName(_fromUtf8("lineEdit_name"))
        self.label_3 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_3.setGeometry(QtCore.QRect(32, 67, 70, 20))
        self.label_3.setMinimumSize(QtCore.QSize(70, 20))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_4.setGeometry(QtCore.QRect(32, 94, 70, 20))
        self.label_4.setMinimumSize(QtCore.QSize(70, 20))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_unit = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_unit.setEnabled(False)
        self.lineEdit_unit.setGeometry(QtCore.QRect(108, 94, 250, 20))
        self.lineEdit_unit.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_unit.setObjectName(_fromUtf8("lineEdit_unit"))
        self.label_5 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_5.setGeometry(QtCore.QRect(32, 121, 70, 20))
        self.label_5.setMinimumSize(QtCore.QSize(70, 20))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_size = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_size.setGeometry(QtCore.QRect(108, 121, 250, 20))
        self.lineEdit_size.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_size.setObjectName(_fromUtf8("lineEdit_size"))
        self.label_6 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_6.setGeometry(QtCore.QRect(32, 148, 70, 20))
        self.label_6.setMinimumSize(QtCore.QSize(70, 20))
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_cost = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_cost.setGeometry(QtCore.QRect(108, 148, 250, 20))
        self.lineEdit_cost.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_cost.setObjectName(_fromUtf8("lineEdit_cost"))
        self.label_7 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_7.setGeometry(QtCore.QRect(32, 175, 70, 20))
        self.label_7.setMinimumSize(QtCore.QSize(70, 20))
        self.label_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_unitcost = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_unitcost.setGeometry(QtCore.QRect(108, 175, 250, 20))
        self.lineEdit_unitcost.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_unitcost.setObjectName(_fromUtf8("lineEdit_unitcost"))
        self.label_10 = QtGui.QLabel(Stat_UnitCostEditor)
        self.label_10.setGeometry(QtCore.QRect(384, 175, 70, 20))
        self.label_10.setMinimumSize(QtCore.QSize(70, 20))
        self.label_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.lineEdit_memo = QtGui.QLineEdit(Stat_UnitCostEditor)
        self.lineEdit_memo.setGeometry(QtCore.QRect(460, 175, 250, 20))
        self.lineEdit_memo.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_memo.setObjectName(_fromUtf8("lineEdit_memo"))

        self.retranslateUi(Stat_UnitCostEditor)
        QtCore.QMetaObject.connectSlotsByName(Stat_UnitCostEditor)

    def retranslateUi(self, Stat_UnitCostEditor):
        Stat_UnitCostEditor.setWindowTitle(_translate("Stat_UnitCostEditor", "Form", None))
        self.tableWidget.setSortingEnabled(True)
        self.btn_load.setText(_translate("Stat_UnitCostEditor", "读入", None))
        self.btn_submit.setText(_translate("Stat_UnitCostEditor", "提交", None))
        self.btn_addrow.setText(_translate("Stat_UnitCostEditor", "增行", None))
        self.btn_delrow.setText(_translate("Stat_UnitCostEditor", "删行", None))
        self.label_8.setText(_translate("Stat_UnitCostEditor", "平均宽", None))
        self.label_9.setText(_translate("Stat_UnitCostEditor", "平均高", None))
        self.label.setText(_translate("Stat_UnitCostEditor", "存货编码", None))
        self.label_2.setText(_translate("Stat_UnitCostEditor", "存货名称", None))
        self.label_3.setText(_translate("Stat_UnitCostEditor", "存货大类", None))
        self.label_4.setText(_translate("Stat_UnitCostEditor", "计量单位", None))
        self.label_5.setText(_translate("Stat_UnitCostEditor", "平均尺寸", None))
        self.label_6.setText(_translate("Stat_UnitCostEditor", "SET原价", None))
        self.label_7.setText(_translate("Stat_UnitCostEditor", "单位原价", None))
        self.label_10.setText(_translate("Stat_UnitCostEditor", "备注", None))

